MENU_INIT = [
    {
        'order': 1,
        'name': "Chicken vindaloo",
        'spicy': 5,
        'description_pol': "Pierś z kurczaka w pikantnym sosie curry z ryżem basmati",
        'description_eng': "Chicken breast in hot tomato gravy with basmati rice",
        'picture_file': "chicken_vindaloo.jpg",
        'is_vegetarian': False,
    },
    {
        'order': 2,
        'name': "Vegetable korma",
        'spicy': 2,
        'description_pol': "Warzywa w sosie jogurtowo-kokosowym z ryżem basmati",
        'description_eng': "Vegetable in coconut gravy with basmati rice",
        'picture_file': "vegetable_korma.jpg",
        'is_vegetarian': True,
    },
    {
        'order': 3,
        'name': "Butter chicken",
        'spicy': 1,
        'description_pol': "Pierś z kurczaka w sosie maślano-pomidorowym z ryżem basmati",
        'description_eng': "Chicken breast in butter and tomato sauce with basmati rice",
        'picture_file': "butter_chicken.jpg",
        'is_vegetarian': False,
    },
    {
        'order': 4,
        'name': "Dal curry",
        'spicy': 3,
        'description_pol': "Fasolka mung z gołębim groszkiem w sosie curry z ryżem basmati",
        'description_eng': "Lentils curry with basmati rice",
        'picture_file': "dal_curry.jpg",
        'is_vegetarian': True,
    },
    {
        'order': 5,
        'name': "Chana masala",
        'spicy': 2,
        'description_pol': "Ciecierzyca w pomidorowym sosie curry z ryżem basmati",
        'description_eng': "Chickpeas in tomato curry sauce with basmati rice",
        'picture_file': "chana_masala.jpg",
        'is_vegetarian': True,
    },
    {
        'order': 6,
        'name': "Chicken curry",
        'spicy': 2,
        'description_pol': "Pierś z kurczaka w jogurtowo-pomidorowym sosie curry z ryżem basmati",
        'description_eng': "Chicken breast in yogurt & tomato curry gravy with basmati rice",
        'picture_file': "chicken_curry.jpg",
        'is_vegetarian': False,
    },
    {
        'order': 7,
        'name': "Chicken korma",
        'spicy': 2,
        'description_pol': "Pierś z kurczaka w sosie jogurtowo-kokosowym z ryżem basmati",
        'description_eng': "Chicken breast in coconut gravy with basmati rice",
        'picture_file': "chicken_korma.jpg",
        'is_vegetarian': False,
    },
    {
        'order': 8,
        'name': "Aloo chana",
        'spicy': 3,
        'description_pol': "Ziemniaki z cieciorką w gęstym sosie curry",
        'description_eng': "Potatoes with chickpeas in curry sauce",
        'picture_file': "aloo_chana.jpg",
        'is_vegetarian': True,
    },
    {
        'order': 9,
        'name': "Chicken madras",
        'spicy': 3,
        'description_pol': "Pierś z kurczaka w sosie madras z ryżem basmati",
        'description_eng': "Chicken breast in madras gravy with basmati rice",
        'picture_file': "chicken_madras.jpg",
        'is_vegetarian': False,
    },
    {
        'order': 10,
        'name': "Pork vindaloo",
        'spicy': 5,
        'description_pol': "Wieprzowina w pikantnym sosie curry z ryżem basmati",
        'description_eng': "Pork in hot tomato gravy with basmati rice",
        'picture_file': "pork_vindaloo.jpg",
        'is_vegetarian': False,
    },
    {
        'order': 11,
        'name': "Chicken palak",
        'spicy': 3,
        'description_pol': "Pierś z kurczaka w sosie szpinakowym z ryżem basmati",
        'description_eng': "Chicken breast in spinach gravy with basmati rice",
        'picture_file': "chicken_palak.jpg",
        'is_vegetarian': False,
    },
    {
        'order': 12,
        'name': "Fish curry",
        'spicy': 3,
        'description_pol': "Filet z ryby w ostrym sosie curry z ryżem basmati",
        'description_eng': "Fish in hot curry gravy with basmati rice",
        'picture_file': "fish_curry.jpg",
        'is_vegetarian': True,
    },
    {
        'order': 13,
        'name': "Rajma masala",
        'spicy': 2,
        'description_pol': "Czerwona fasolka w sosie pomidorowym z ryżem basmati",
        'description_eng': "Red kidney beans in tomato gravy with basmati rice",
        'picture_file': "rajma_masala.jpg",
        'is_vegetarian': True,
    },
    {
        'order': 14,
        'name': "Chicken tikka masala",
        'spicy': 4,
        'description_pol': "Pierś z kurczaka w sosie tikka masala z ryżem basmati",
        'description_eng': "Chicken breast in tikka masala sauce with basmati rice",
        'picture_file': "chicken_tikka.jpg",
        'is_vegetarian': False,
    },
    {
        'order': 15,
        'name': "Chicken vindaloo",
        'spicy': 5,
        'description_pol': "Pierś z kurczaka w pikantnym sosie curry z ryżem basmati",
        'description_eng': "Chicken breast in hot tomato gravy with basmati rice",
        'picture_file': "chicken_vindaloo.jpg",
        'is_vegetarian': False,
    },
    {
        'order': 16,
        'name': "Kerala pork",
        'spicy': 3,
        'description_pol': "Lekko pikantne curry z wieprzowiny z ryżem basmati",
        'description_eng': "Pork curry in kerala style with basmati rice",
        'picture_file': "kerala_pork.jpg",
        'is_vegetarian': False,
    },
    {
        'order': 17,
        'name': "Warzywa curry",
        'spicy': 2,
        'description_pol': "Warzywa w pomidorowym sosie curry z ryżem basmati",
        'description_eng': "Vegetables in tomato curry sauce with basmati rice",
        'picture_file': "warzywa_curry.jpg",
        'is_vegetarian': True,
    },
    {
        'order': 18,
        'name': "Dal makhani",
        'spicy': 2,
        'description_pol': "Soczewica urid z czerwoną fasolą w pomidorowo maślanym sosie z ryżem basmati",
        'description_eng': "Black lentils and red kidney beans in butter gravy with basmati rice",
        'picture_file': "dal_makhani.jpg",
        'is_vegetarian': True,
    },
]
