# Generated by Django 3.1.1 on 2020-09-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='picture',
            new_name='picture_url',
        ),
        migrations.AlterField(
            model_name='dish',
            name='description_eng',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description_pol',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='dish',
            name='is_cooked_today',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dish',
            name='spicy',
            field=models.IntegerField(choices=[(1, 'Łagodny Hindus'), (2, 'Lekko pikantny Hindus'), (3, 'Średnio pikantny Hindus'), (4, 'Mocno pikantny Hindus'), (5, 'Ostry Hindus')], default=1),
        ),
    ]
